// Language Toggle System for Vue.js
const LanguageToggle = {
    translations: {
        // Bundle Index
        'bundle': {
            id: {
                'title': 'INKTATTOO',
                'subtitle': 'Paket Website Lengkap',
                'welcome-title': 'Selamat Datang di Paket INK Tattoo Studio',
                'welcome-desc': 'Paket lengkap website tattoo studio dengan berbagai template, dashboard backend, dan proposal digital marketing. Semua template sudah responsive, mobile-friendly, dan siap digunakan.',
                'templates': 'Template',
                'package-features': 'Fitur Paket',
                'fully-responsive': 'Fully Responsive',
                'fully-responsive-desc': 'Semua template responsive dan mobile-friendly untuk semua perangkat.',
                'booking-system': 'Booking System',
                'booking-system-desc': 'Sistem booking terintegrasi dengan Google Calendar untuk setiap artist.',
                'multiple-themes': 'Multiple Themes',
                'multiple-themes-desc': '2 tema berbeda (Dark & White Black) sesuai kebutuhan branding.',
                'need-help': 'Butuh Bantuan?',
                'contact-desc': 'Hubungi kami untuk dukungan atau pertanyaan tentang paket ini',
                'footer-text': '© 2024 INK Tattoo Studio - Bundle Package. All rights reserved.'
            },
            en: {
                'title': 'INKTATTOO',
                'subtitle': 'Complete Website Package',
                'welcome-title': 'Welcome to INK Tattoo Studio Package',
                'welcome-desc': 'Complete tattoo studio website package with various templates, backend dashboard, and digital marketing proposal. All templates are responsive, mobile-friendly, and ready to use.',
                'templates': 'Templates',
                'package-features': 'Package Features',
                'fully-responsive': 'Fully Responsive',
                'fully-responsive-desc': 'All templates are responsive and mobile-friendly for all devices.',
                'booking-system': 'Booking System',
                'booking-system-desc': 'Integrated booking system with Google Calendar for each artist.',
                'multiple-themes': 'Multiple Themes',
                'multiple-themes-desc': '2 different themes (Dark & White Black) according to branding needs.',
                'need-help': 'Need Help?',
                'contact-desc': 'Contact us for support or questions about this package',
                'footer-text': '© 2024 INK Tattoo Studio - Bundle Package. All rights reserved.'
            }
        },
        
        // Proposal (Template 8)
        'proposal': {
            id: {
                'back-to-home': 'Kembali ke Beranda',
                'proposal-title': 'PROPOSAL',
                'proposal-subtitle': 'Layanan Website & Digital Marketing',
                'proposal-location': 'Tattoo Studio - 3 Cabang Bali',
                'project-info': 'INFORMASI PROYEK',
                'client-name': 'Nama Klien:',
                'client-value': 'Tattoo Studio (3 Cabang Bali)',
                'contract-period': 'Periode Kontrak:',
                'contract-value': '6 Bulan / 1 Tahun (opsional)',
                'proposal-date': 'Tanggal Proposal:',
                'proposal-date-value': '2024',
                'status': 'Status:',
                'status-value': 'Draft',
                'executive-summary': 'RINGKASAN EKSEKUTIF',
                'executive-summary-text': 'Proposal ini mencakup pengembangan website profesional untuk 3 cabang tattoo studio di Bali dengan fitur booking system terintegrasi Google Calendar, serta layanan SEO, Social Media Management, dan Periklanan Digital untuk meningkatkan visibilitas dan konversi bisnis.',
                'services-offered': 'LAYANAN YANG DITAWARKAN',
                'website-development': '1. PENGEMBANGAN WEBSITE',
                'main-features': 'Fitur Utama Website:',
                'seo-service': '2. LAYANAN SEO',
                'seo-goal': 'Tujuan:',
                'seo-goal-text': 'Meningkatkan ranking website di Google agar muncul di halaman pertama hasil pencarian, sehingga lebih banyak calon customer menemukan studio tattoo Anda secara organik (tanpa iklan berbayar).',
                'social-media': '3. SOCIAL MEDIA MANAGEMENT',
                'digital-advertising': '4. PERIKLANAN DIGITAL',
                'photo-video': '5. LAYANAN FOTO & VIDEO',
                'photo-video-price': 'Harga per kunjungan:',
                'photo-video-price-value': 'Rp 1.250.000 (foto & video)',
                'services-included': 'Layanan yang termasuk:',
                'photo': 'Foto:',
                'photo-value': 'Foto edited all in (unlimited)',
                'video': 'Video:',
                'video-value': 'Video reel portrait 1 menit sampai 1.30 menit',
                'quantity': 'Kuantitas:',
                'quantity-value': '4 video per bulan, total foto unlimited',
                'attendance': 'Kehadiran:',
                'attendance-value': '4 kali per bulan',
                'include': 'Include:',
                'include-value': 'All gears (camera, lens, lighting) dan editing',
                'package-summary': 'Ringkasan Paket:',
                'total-video': 'Total video: 4 buah per bulan',
                'total-photo': 'Total foto: Unlimited (edited all in)',
                'attendance-summary': 'Kehadiran: 4 kali per bulan',
                'include-summary': 'Include all gears (camera, lens, lighting) dan editing',
                'pricing-packages': 'PAKET HARGA',
                'package-6-months': 'PAKET 6 BULAN',
                'package-1-year': 'PAKET 1 TAHUN',
                'recommended': 'RECOMMENDED',
                'save-amount': 'Hemat Rp 17.770.000 (Diskon 15%)',
                'item': 'Item',
                'price': 'Harga',
                'payment': 'Pembayaran:',
                'down-payment': 'Down Payment:',
                'installment': 'Cicilan',
                'per-month': '/bulan',
                'what-you-get': 'YANG AKAN DITERIMA KLIEN',
                'development-phase': 'TAHAP PENGEMBANGAN (Bulan 1-2)',
                'operational-phase': 'TAHAP OPERASIONAL (Bulan 3-6/12)',
                'seo-timeline': 'TIMELINE SEO (DIMULAI BULAN 2)',
                'timeline-deliverables': 'TIMELINE & DELIVERABLES',
                'benefits': 'KEUNTUNGAN PAKET INI',
                'important-notes': 'CATATAN PENTING',
                'guarantee-support': 'GARANSI & SUPPORT',
                'next-steps': 'NEXT STEPS',
                'contact-questions': 'KONTAK UNTUK PERTANYAAN',
                'email': 'Email',
                'whatsapp': 'WhatsApp',
                'website': 'Website',
                'website-feature-1': 'Multi-branch System: Website untuk 3 cabang dengan manajemen terpusat',
                'website-feature-2': 'Artist Profile Pages: Halaman profil untuk setiap artist dengan portfolio',
                'website-feature-3': 'Booking System Terintegrasi: Sistem booking real-time dengan Google Calendar',
                'website-feature-4': 'Portfolio Gallery: Galeri foto hasil tattoo per artist',
                'website-feature-5': 'Contact Forms: Formulir kontak per cabang',
                'website-feature-6': 'Responsive Design: Mobile-friendly untuk semua perangkat',
                'website-feature-7': 'Multi-language Support: Bahasa Indonesia & Inggris (opsional)',
                'timeline-development': 'Timeline Pengembangan:',
                'timeline-total': 'Total: 8 minggu (2 bulan)',
                'on-page-seo': 'On-Page SEO',
                'on-page-seo-desc': 'Optimasi konten & struktur website:',
                'on-page-seo-1': 'Meta tags, title, description',
                'on-page-seo-2': 'Optimasi gambar & URL',
                'on-page-seo-3': 'Internal linking',
                'off-page-seo': 'Off-Page SEO',
                'off-page-seo-desc': 'Membangun otoritas website:',
                'off-page-seo-1': 'Link building (5-10 backlinks/bulan)',
                'off-page-seo-2': 'Local SEO (Google Business)',
                'off-page-seo-3': 'Directory submissions',
                'technical-seo': 'Technical SEO',
                'technical-seo-desc': 'Optimasi teknis website:',
                'technical-seo-1': 'Sitemap, robots.txt',
                'technical-seo-2': 'Page speed optimization',
                'technical-seo-3': 'Analytics & tracking',
                'seo-expected-results': 'Hasil yang Diharapkan:',
                'seo-result-1': 'Website muncul di halaman 1 Google untuk keyword "tattoo bali", "tattoo studio uluwatu", dll',
                'seo-result-2': 'Traffic organik meningkat (calon customer menemukan website tanpa iklan)',
                'seo-result-3': 'Booking meningkat dari pencarian Google',
                'seo-result-4': 'Monthly SEO report dengan tracking keyword ranking & traffic',
                'smm-note': 'Catatan:',
                'smm-note-text': 'Kami hanya melakukan posting konten. Desain/gambar/video disediakan oleh client. Kami akan posting sesuai jadwal yang telah disepakati.',
                'smm-platform': 'Platform:',
                'smm-platform-value': 'Instagram, Facebook, TikTok (opsional), Google Business Profile',
                'smm-services': 'Layanan:',
                'smm-service-1': 'Posting konten yang disediakan client (15-20 posts per bulan per platform)',
                'smm-service-2': 'Daily stories update (jika konten tersedia)',
                'smm-service-3': 'Response to comments & DMs',
                'smm-service-4': 'Community management',
                'smm-service-5': 'Hashtag research & optimization',
                'smm-service-6': 'Monthly SMM report',
                'smm-not-included': 'Tidak termasuk:',
                'smm-not-included-text': 'Desain konten, photography, videography (disediakan oleh client)',
                'ads-note': 'Catatan:',
                'ads-note-text': 'Kami hanya melakukan management campaign. Desain kreatif iklan dan budget iklan (dibayar langsung ke platform) disediakan/dibayar oleh client sendiri.',
                'ads-services-included': 'Layanan yang termasuk:',
                'ads-service-1': 'Campaign setup & strategy',
                'ads-service-2': 'Account setup (Google Ads, Facebook Ads)',
                'ads-service-3': 'Campaign management & optimization',
                'ads-service-4': 'Budget management (menggunakan budget dari client)',
                'ads-service-5': 'A/B testing',
                'ads-service-6': 'Performance monitoring',
                'ads-service-7': 'Tracking & conversion setup',
                'ads-service-8': 'Monthly ads performance report',
                'google-ads': 'Google Ads',
                'google-ads-1': 'Google Search Ads',
                'google-ads-2': 'Google Display Ads',
                'google-ads-3': 'Google Local Ads',
                'social-media-ads': 'Social Media Ads',
                'social-ads-1': 'Instagram/Facebook Ads',
                'social-ads-2': 'Targeted campaigns',
                'social-ads-3': 'Retargeting campaigns',
                'ads-not-included': 'Tidak termasuk:',
                'ads-not-included-1': 'Desain kreatif iklan (disediakan oleh client)',
                'ads-not-included-2': 'Budget iklan (dibayar langsung oleh client ke platform iklan)',
                'package-6-price': 'Rp 78.500.000',
                'package-1-year-price': 'Rp 99.530.000',
                'table-item': 'Item',
                'table-price': 'Harga',
                'item-website-dev': 'Website Development',
                'item-website-dev-price': 'Rp 10.000.000',
                'item-calendar': 'Google Calendar Integration',
                'item-calendar-price': 'Rp 5.000.000',
                'item-hosting-1': 'Hosting & Domain (1 tahun)',
                'item-hosting-12': 'Hosting & Domain (12 bulan)',
                'item-hosting-price': 'Rp 2.000.000',
                'item-ssl-1': 'SSL Certificate',
                'item-ssl-price-1': 'Rp 500.000',
                'item-ssl-price-12': 'Rp 1.000.000',
                'item-maintenance-6': 'Maintenance (6 bulan)',
                'item-maintenance-12': 'Maintenance (12 bulan)',
                'item-maintenance-6-price': 'Rp 6.000.000',
                'item-maintenance-12-price': 'Rp 10.000.000',
                'item-seo-6': 'SEO Setup & Service',
                'item-seo-6-price': 'Rp 35.000.000',
                'item-seo-12': 'SEO Setup & Service',
                'item-seo-12-price': 'Rp 56.000.000',
                'item-smm-6': 'SMM Setup & Service',
                'item-smm-6-price': 'Rp 10.000.000',
                'item-smm-12': 'SMM Setup & Service',
                'item-smm-12-price': 'Rp 15.600.000',
                'item-ads-6': 'Ads Setup & Management',
                'item-ads-6-price': 'Rp 10.000.000',
                'item-ads-12': 'Ads Setup & Management',
                'item-ads-12-price': 'Rp 15.600.000',
                'down-payment-6': 'Rp 30.000.000',
                'down-payment-12': 'Rp 40.000.000',
                'installment-6': 'Rp 8.083.333',
                'installment-12': 'Rp 4.960.833',
                'dev-phase-1': 'Website profesional untuk 3 cabang',
                'dev-phase-2': 'Domain & hosting aktif',
                'dev-phase-3': 'SSL certificate terpasang',
                'dev-phase-4': 'Booking system berfungsi',
                'dev-phase-5': 'Integrasi Google Calendar aktif',
                'dev-phase-6': 'Training & dokumentasi',
                'op-phase-1': 'Layanan SEO bulanan',
                'op-phase-2': 'Social Media Management',
                'op-phase-3': 'Digital Advertising campaigns',
                'op-phase-4': 'Monthly reports',
                'op-phase-5': 'Support & maintenance',
                'op-phase-6': 'Technical support 24/7',
                'seo-timeline-note': 'Catatan:',
                'seo-timeline-note-text': 'SEO dimulai di Bulan 2 setelah website selesai dikembangkan. Client akan menerima layanan SEO selama 5 bulan (Bulan 2-6 untuk paket 6 bulan, atau Bulan 2-12 untuk paket 1 tahun).',
                'seo-month-2': 'BULAN 2: SEO SETUP & OPTIMIZATION',
                'seo-month-2-1': 'SEO Audit:',
                'seo-month-2-1-text': 'Analisis website lengkap',
                'seo-month-2-2': 'Keyword Research:',
                'seo-month-2-2-text': 'Daftar keyword target',
                'seo-month-2-3': 'On-page Optimization:',
                'seo-month-2-3-text': 'Optimasi meta tags, title, description',
                'seo-month-2-4': 'Technical SEO:',
                'seo-month-2-4-text': 'Sitemap, robots.txt, schema markup',
                'seo-month-2-5': 'Deliverables:',
                'seo-month-2-5-text': 'SEO audit report, keyword list, optimized website',
                'seo-month-3-6': 'BULAN 3-6: SEO MONTHLY SERVICE',
                'seo-monthly-desc': 'Setiap bulan client akan menerima:',
                'seo-monthly-1': 'On-page Optimization:',
                'seo-monthly-1-text': 'Update konten, optimasi halaman',
                'seo-monthly-2': 'Off-page SEO:',
                'seo-monthly-2-text': '5-10 backlink building per bulan',
                'seo-monthly-3': 'Content Optimization:',
                'seo-monthly-3-text': 'Optimasi konten existing',
                'seo-monthly-4': 'Technical SEO:',
                'seo-monthly-4-text': 'Maintenance & monitoring',
                'seo-monthly-5': 'Monthly SEO Report:',
                'seo-monthly-5-text': 'Keyword ranking, traffic analysis, recommendations',
                'seo-receive-title': 'YANG AKAN DITERIMA CLIENT SELAMA 5 BULAN (BULAN 2-6):',
                'seo-month-2-receive-1': 'SEO Audit Report',
                'seo-month-2-receive-2': 'Keyword Research Document',
                'seo-month-2-receive-3': 'Website Optimization (on-page)',
                'seo-month-2-receive-4': 'Technical SEO Setup',
                'seo-month-3-6-receive-1': '5-10 Backlinks (total 20-40 backlinks)',
                'seo-month-3-6-receive-2': 'Content Optimization',
                'seo-month-3-6-receive-3': 'Technical SEO Maintenance',
                'seo-month-3-6-receive-4': 'Monthly SEO Report dengan:',
                'seo-report-1': 'Keyword ranking tracking',
                'seo-report-2': 'Traffic analysis',
                'seo-report-3': 'Conversion tracking',
                'seo-report-4': 'Recommendations',
                'timeline-month-1-2': 'BULAN 1-2: PENGEMBANGAN',
                'timeline-week-1-2': 'Week 1-2: Design & Planning',
                'timeline-week-3-4': 'Week 3-4: Development',
                'timeline-week-5-6': 'Week 5-6: Integration & Testing',
                'timeline-week-7-8': 'Week 7-8: Launch & Training',
                'timeline-month-2-6': 'BULAN 2-6/12: OPERASIONAL',
                'timeline-month-2': 'Bulan 2:',
                'timeline-month-2-text': 'SEO Setup & Optimization',
                'timeline-month-3-6': 'Bulan 3-6:',
                'timeline-month-3-6-text': 'SEO monthly service + reports',
                'timeline-other-1': 'Social media content & management',
                'timeline-other-2': 'Digital advertising campaigns',
                'timeline-other-3': 'Monthly reports & meetings',
                'benefit-1-title': 'All-in-One Solution',
                'benefit-1-desc': 'Website + SEO + SMM + Ads dalam satu paket',
                'benefit-2-title': 'Cost Effective',
                'benefit-2-desc': 'Lebih hemat dibanding hire multiple vendors',
                'benefit-3-title': 'Data-Driven',
                'benefit-3-desc': 'Analytics & reporting untuk decision making',
                'important-note-1': 'SMM (Social Media Management):',
                'important-note-1-text': 'Kami hanya melakukan posting konten. Desain/gambar/video untuk posting disediakan oleh client. Kami akan posting sesuai jadwal yang telah disepakati.',
                'important-note-2': 'Ads Management:',
                'important-note-2-text': 'Kami hanya melakukan management campaign. Desain kreatif iklan dan budget iklan (dibayar langsung ke platform) disediakan/dibayar oleh client sendiri.',
                'important-note-3': 'Konten Foto/Video:',
                'important-note-3-text': 'Semua konten untuk SMM dan Ads disediakan oleh client',
                'important-note-4': 'Domain & Hosting:',
                'important-note-4-text': 'Renewal tahun berikutnya dengan harga normal',
                'important-note-5': 'Additional Features:',
                'important-note-5-text': 'Fitur tambahan bisa dinegosiasikan dengan biaya terpisah',
                'important-note-6': 'Revisi Design:',
                'important-note-6-text': 'Maksimal 3x revisi untuk design website',
                'guarantee-1-title': 'Website Uptime',
                'guarantee-1-desc': '99.9% uptime guarantee',
                'guarantee-2-title': 'Response Time',
                'guarantee-2-desc': 'Maksimal 24 jam untuk support requests',
                'guarantee-3-title': 'Bug Fixes',
                'guarantee-3-desc': 'Gratis selama periode kontrak',
                'guarantee-4-title': 'Backup',
                'guarantee-4-desc': 'Daily automated backups',
                'next-step-1': 'Review proposal ini',
                'next-step-2': 'Pilih paket (6 bulan atau 1 tahun)',
                'next-step-3': 'Meeting untuk diskusi detail',
                'next-step-4': 'Sign kontrak & down payment',
                'next-step-5': 'Kick-off meeting & project start',
                'footer-note': 'Proposal ini berlaku selama 30 hari sejak tanggal diterbitkan.'
            },
            en: {
                'back-to-home': 'Back to Home',
                'proposal-title': 'PROPOSAL',
                'proposal-subtitle': 'Website & Digital Marketing Services',
                'proposal-location': 'Tattoo Studio - 3 Branches Bali',
                'project-info': 'PROJECT INFORMATION',
                'client-name': 'Client Name:',
                'client-value': 'Tattoo Studio (3 Branches Bali)',
                'contract-period': 'Contract Period:',
                'contract-value': '6 Months / 1 Year (optional)',
                'proposal-date': 'Proposal Date:',
                'proposal-date-value': '2024',
                'status': 'Status:',
                'status-value': 'Draft',
                'executive-summary': 'EXECUTIVE SUMMARY',
                'executive-summary-text': 'This proposal includes professional website development for 3 tattoo studio branches in Bali with integrated Google Calendar booking system, as well as SEO services, Social Media Management, and Digital Advertising to increase visibility and business conversion.',
                'services-offered': 'SERVICES OFFERED',
                'website-development': '1. WEBSITE DEVELOPMENT',
                'main-features': 'Main Website Features:',
                'seo-service': '2. SEO SERVICES',
                'seo-goal': 'Goal:',
                'seo-goal-text': 'Improve website ranking on Google to appear on the first page of search results, so more potential customers find your tattoo studio organically (without paid advertising).',
                'social-media': '3. SOCIAL MEDIA MANAGEMENT',
                'digital-advertising': '4. DIGITAL ADVERTISING',
                'photo-video': '5. PHOTOGRAPHY & VIDEOGRAPHY SERVICES',
                'photo-video-price': 'Price per visit:',
                'photo-video-price-value': 'Rp 1,250,000 (photo & video)',
                'services-included': 'Services included:',
                'photo': 'Photo:',
                'photo-value': 'Photo edited all in (unlimited)',
                'video': 'Video:',
                'video-value': 'Video reel portrait 1 minute to 1.30 minutes',
                'quantity': 'Quantity:',
                'quantity-value': '4 videos per month, total photos unlimited',
                'attendance': 'Attendance:',
                'attendance-value': '4 times per month',
                'include': 'Include:',
                'include-value': 'All gears (camera, lens, lighting) and editing',
                'package-summary': 'Package Summary:',
                'total-video': 'Total video: 4 pieces per month',
                'total-photo': 'Total photos: Unlimited (edited all in)',
                'attendance-summary': 'Attendance: 4 times per month',
                'include-summary': 'Include all gears (camera, lens, lighting) and editing',
                'pricing-packages': 'PRICING PACKAGES',
                'package-6-months': '6 MONTHS PACKAGE',
                'package-1-year': '1 YEAR PACKAGE',
                'recommended': 'RECOMMENDED',
                'save-amount': 'Save Rp 17,770,000 (15% Discount)',
                'item': 'Item',
                'price': 'Price',
                'payment': 'Payment:',
                'down-payment': 'Down Payment:',
                'installment': 'Installment',
                'per-month': '/month',
                'what-you-get': 'WHAT CLIENT WILL RECEIVE',
                'development-phase': 'DEVELOPMENT PHASE (Month 1-2)',
                'operational-phase': 'OPERATIONAL PHASE (Month 3-6/12)',
                'seo-timeline': 'SEO TIMELINE (STARTING MONTH 2)',
                'timeline-deliverables': 'TIMELINE & DELIVERABLES',
                'benefits': 'PACKAGE BENEFITS',
                'important-notes': 'IMPORTANT NOTES',
                'guarantee-support': 'GUARANTEE & SUPPORT',
                'next-steps': 'NEXT STEPS',
                'contact-questions': 'CONTACT FOR QUESTIONS',
                'email': 'Email',
                'whatsapp': 'WhatsApp',
                'website': 'Website',
                'website-feature-1': 'Multi-branch System: Website for 3 branches with centralized management',
                'website-feature-2': 'Artist Profile Pages: Profile pages for each artist with portfolio',
                'website-feature-3': 'Integrated Booking System: Real-time booking system with Google Calendar',
                'website-feature-4': 'Portfolio Gallery: Photo gallery of tattoo results per artist',
                'website-feature-5': 'Contact Forms: Contact forms per branch',
                'website-feature-6': 'Responsive Design: Mobile-friendly for all devices',
                'website-feature-7': 'Multi-language Support: Indonesian & English (optional)',
                'timeline-development': 'Development Timeline:',
                'timeline-total': 'Total: 8 weeks (2 months)',
                'on-page-seo': 'On-Page SEO',
                'on-page-seo-desc': 'Content & website structure optimization:',
                'on-page-seo-1': 'Meta tags, title, description',
                'on-page-seo-2': 'Image & URL optimization',
                'on-page-seo-3': 'Internal linking',
                'off-page-seo': 'Off-Page SEO',
                'off-page-seo-desc': 'Building website authority:',
                'off-page-seo-1': 'Link building (5-10 backlinks/month)',
                'off-page-seo-2': 'Local SEO (Google Business)',
                'off-page-seo-3': 'Directory submissions',
                'technical-seo': 'Technical SEO',
                'technical-seo-desc': 'Website technical optimization:',
                'technical-seo-1': 'Sitemap, robots.txt',
                'technical-seo-2': 'Page speed optimization',
                'technical-seo-3': 'Analytics & tracking',
                'seo-expected-results': 'Expected Results:',
                'seo-result-1': 'Website appears on page 1 of Google for keywords "tattoo bali", "tattoo studio uluwatu", etc',
                'seo-result-2': 'Organic traffic increases (potential customers find website without ads)',
                'seo-result-3': 'Bookings increase from Google search',
                'seo-result-4': 'Monthly SEO report with keyword ranking & traffic tracking',
                'smm-note': 'Note:',
                'smm-note-text': 'We only perform content posting. Design/images/videos are provided by client. We will post according to agreed schedule.',
                'smm-platform': 'Platform:',
                'smm-platform-value': 'Instagram, Facebook, TikTok (optional), Google Business Profile',
                'smm-services': 'Services:',
                'smm-service-1': 'Posting content provided by client (15-20 posts per month per platform)',
                'smm-service-2': 'Daily stories update (if content available)',
                'smm-service-3': 'Response to comments & DMs',
                'smm-service-4': 'Community management',
                'smm-service-5': 'Hashtag research & optimization',
                'smm-service-6': 'Monthly SMM report',
                'smm-not-included': 'Not included:',
                'smm-not-included-text': 'Content design, photography, videography (provided by client)',
                'ads-note': 'Note:',
                'ads-note-text': 'We only perform campaign management. Creative ad design and ad budget (paid directly to platform) are provided/paid by client themselves.',
                'ads-services-included': 'Services included:',
                'ads-service-1': 'Campaign setup & strategy',
                'ads-service-2': 'Account setup (Google Ads, Facebook Ads)',
                'ads-service-3': 'Campaign management & optimization',
                'ads-service-4': 'Budget management (using client budget)',
                'ads-service-5': 'A/B testing',
                'ads-service-6': 'Performance monitoring',
                'ads-service-7': 'Tracking & conversion setup',
                'ads-service-8': 'Monthly ads performance report',
                'google-ads': 'Google Ads',
                'google-ads-1': 'Google Search Ads',
                'google-ads-2': 'Google Display Ads',
                'google-ads-3': 'Google Local Ads',
                'social-media-ads': 'Social Media Ads',
                'social-ads-1': 'Instagram/Facebook Ads',
                'social-ads-2': 'Targeted campaigns',
                'social-ads-3': 'Retargeting campaigns',
                'ads-not-included': 'Not included:',
                'ads-not-included-1': 'Creative ad design (provided by client)',
                'ads-not-included-2': 'Ad budget (paid directly by client to ad platform)',
                'package-6-price': 'Rp 78,500,000',
                'package-1-year-price': 'Rp 99,530,000',
                'table-item': 'Item',
                'table-price': 'Price',
                'item-website-dev': 'Website Development',
                'item-website-dev-price': 'Rp 10,000,000',
                'item-calendar': 'Google Calendar Integration',
                'item-calendar-price': 'Rp 5,000,000',
                'item-hosting-1': 'Hosting & Domain (1 year)',
                'item-hosting-12': 'Hosting & Domain (12 months)',
                'item-hosting-price': 'Rp 2,000,000',
                'item-ssl-1': 'SSL Certificate',
                'item-ssl-price-1': 'Rp 500,000',
                'item-ssl-price-12': 'Rp 1,000,000',
                'item-maintenance-6': 'Maintenance (6 months)',
                'item-maintenance-12': 'Maintenance (12 months)',
                'item-maintenance-6-price': 'Rp 6,000,000',
                'item-maintenance-12-price': 'Rp 10,000,000',
                'item-seo-6': 'SEO Setup & Service',
                'item-seo-6-price': 'Rp 35,000,000',
                'item-seo-12': 'SEO Setup & Service',
                'item-seo-12-price': 'Rp 56,000,000',
                'item-smm-6': 'SMM Setup & Service',
                'item-smm-6-price': 'Rp 10,000,000',
                'item-smm-12': 'SMM Setup & Service',
                'item-smm-12-price': 'Rp 15,600,000',
                'item-ads-6': 'Ads Setup & Management',
                'item-ads-6-price': 'Rp 10,000,000',
                'item-ads-12': 'Ads Setup & Management',
                'item-ads-12-price': 'Rp 15,600,000',
                'down-payment-6': 'Rp 30,000,000',
                'down-payment-12': 'Rp 40,000,000',
                'installment-6': 'Rp 8,083,333',
                'installment-12': 'Rp 4,960,833',
                'dev-phase-1': 'Professional website for 3 branches',
                'dev-phase-2': 'Domain & hosting active',
                'dev-phase-3': 'SSL certificate installed',
                'dev-phase-4': 'Booking system functional',
                'dev-phase-5': 'Google Calendar integration active',
                'dev-phase-6': 'Training & documentation',
                'op-phase-1': 'Monthly SEO services',
                'op-phase-2': 'Social Media Management',
                'op-phase-3': 'Digital Advertising campaigns',
                'op-phase-4': 'Monthly reports',
                'op-phase-5': 'Support & maintenance',
                'op-phase-6': 'Technical support 24/7',
                'seo-timeline-note': 'Note:',
                'seo-timeline-note-text': 'SEO starts in Month 2 after website development is completed. Client will receive SEO services for 5 months (Month 2-6 for 6-month package, or Month 2-12 for 1-year package).',
                'seo-month-2': 'MONTH 2: SEO SETUP & OPTIMIZATION',
                'seo-month-2-1': 'SEO Audit:',
                'seo-month-2-1-text': 'Complete website analysis',
                'seo-month-2-2': 'Keyword Research:',
                'seo-month-2-2-text': 'Target keyword list',
                'seo-month-2-3': 'On-page Optimization:',
                'seo-month-2-3-text': 'Meta tags, title, description optimization',
                'seo-month-2-4': 'Technical SEO:',
                'seo-month-2-4-text': 'Sitemap, robots.txt, schema markup',
                'seo-month-2-5': 'Deliverables:',
                'seo-month-2-5-text': 'SEO audit report, keyword list, optimized website',
                'seo-month-3-6': 'MONTH 3-6: SEO MONTHLY SERVICE',
                'seo-monthly-desc': 'Each month client will receive:',
                'seo-monthly-1': 'On-page Optimization:',
                'seo-monthly-1-text': 'Content updates, page optimization',
                'seo-monthly-2': 'Off-page SEO:',
                'seo-monthly-2-text': '5-10 backlink building per month',
                'seo-monthly-3': 'Content Optimization:',
                'seo-monthly-3-text': 'Existing content optimization',
                'seo-monthly-4': 'Technical SEO:',
                'seo-monthly-4-text': 'Maintenance & monitoring',
                'seo-monthly-5': 'Monthly SEO Report:',
                'seo-monthly-5-text': 'Keyword ranking, traffic analysis, recommendations',
                'seo-receive-title': 'WHAT CLIENT WILL RECEIVE DURING 5 MONTHS (MONTH 2-6):',
                'seo-month-2-receive-1': 'SEO Audit Report',
                'seo-month-2-receive-2': 'Keyword Research Document',
                'seo-month-2-receive-3': 'Website Optimization (on-page)',
                'seo-month-2-receive-4': 'Technical SEO Setup',
                'seo-month-3-6-receive-1': '5-10 Backlinks (total 20-40 backlinks)',
                'seo-month-3-6-receive-2': 'Content Optimization',
                'seo-month-3-6-receive-3': 'Technical SEO Maintenance',
                'seo-month-3-6-receive-4': 'Monthly SEO Report with:',
                'seo-report-1': 'Keyword ranking tracking',
                'seo-report-2': 'Traffic analysis',
                'seo-report-3': 'Conversion tracking',
                'seo-report-4': 'Recommendations',
                'timeline-month-1-2': 'MONTH 1-2: DEVELOPMENT',
                'timeline-week-1-2': 'Week 1-2: Design & Planning',
                'timeline-week-3-4': 'Week 3-4: Development',
                'timeline-week-5-6': 'Week 5-6: Integration & Testing',
                'timeline-week-7-8': 'Week 7-8: Launch & Training',
                'timeline-month-2-6': 'MONTH 2-6/12: OPERATIONAL',
                'timeline-month-2': 'Month 2:',
                'timeline-month-2-text': 'SEO Setup & Optimization',
                'timeline-month-3-6': 'Month 3-6:',
                'timeline-month-3-6-text': 'SEO monthly service + reports',
                'timeline-other-1': 'Social media content & management',
                'timeline-other-2': 'Digital advertising campaigns',
                'timeline-other-3': 'Monthly reports & meetings',
                'benefit-1-title': 'All-in-One Solution',
                'benefit-1-desc': 'Website + SEO + SMM + Ads in one package',
                'benefit-2-title': 'Cost Effective',
                'benefit-2-desc': 'More cost-effective than hiring multiple vendors',
                'benefit-3-title': 'Data-Driven',
                'benefit-3-desc': 'Analytics & reporting for decision making',
                'important-note-1': 'SMM (Social Media Management):',
                'important-note-1-text': 'We only perform content posting. Design/images/videos for posting are provided by client. We will post according to agreed schedule.',
                'important-note-2': 'Ads Management:',
                'important-note-2-text': 'We only perform campaign management. Creative ad design and ad budget (paid directly to platform) are provided/paid by client themselves.',
                'important-note-3': 'Photo/Video Content:',
                'important-note-3-text': 'All content for SMM and Ads is provided by client',
                'important-note-4': 'Domain & Hosting:',
                'important-note-4-text': 'Renewal for next year at normal price',
                'important-note-5': 'Additional Features:',
                'important-note-5-text': 'Additional features can be negotiated with separate cost',
                'important-note-6': 'Design Revisions:',
                'important-note-6-text': 'Maximum 3 revisions for website design',
                'guarantee-1-title': 'Website Uptime',
                'guarantee-1-desc': '99.9% uptime guarantee',
                'guarantee-2-title': 'Response Time',
                'guarantee-2-desc': 'Maximum 24 hours for support requests',
                'guarantee-3-title': 'Bug Fixes',
                'guarantee-3-desc': 'Free during contract period',
                'guarantee-4-title': 'Backup',
                'guarantee-4-desc': 'Daily automated backups',
                'next-step-1': 'Review this proposal',
                'next-step-2': 'Choose package (6 months or 1 year)',
                'next-step-3': 'Meeting for detailed discussion',
                'next-step-4': 'Sign contract & down payment',
                'next-step-5': 'Kick-off meeting & project start',
                'footer-note': 'This proposal is valid for 30 days from the date of issue.'
            }
        },
        
        // Template 4 & 5 (Frontend)
        'frontend': {
            id: {
                'tattoo-studio': 'Tattoo Studio',
                'bali': 'Bali',
                'premium-locations': '3 Lokasi Premium: Uluwatu • Canggu • Denpasar',
                'book-now': 'Pesan Sekarang',
                'view-portfolio': 'Lihat Portfolio',
                'our-studios': 'Studio Kami',
                'about-us': 'Tentang Kami',
                'our-story': 'Cerita Kami',
                'our-story-text': 'INKBALI adalah studio tattoo premium dengan tiga lokasi di seluruh Bali. Kami mengkhususkan diri dalam menciptakan tattoo unik dan berkualitas tinggi yang mencerminkan gaya dan cerita pribadi Anda. Tim artist profesional kami membawa pengalaman bertahun-tahun dan keunggulan artistik ke setiap karya.',
                'why-choose-us': 'Mengapa Pilih Kami',
                'professional-artists': 'Artist profesional dengan pengalaman bertahun-tahun',
                'premium-quality': 'Tinta dan peralatan berkualitas premium',
                'sterile-safe': 'Lingkungan steril dan aman',
                'convenient-locations': '3 lokasi nyaman di Bali',
                'portfolio': 'Portfolio',
                'graywash-black-gray': 'GRAYWASH / BLACK AND GRAY',
                'small-fineline-script': 'SMALL - FINELINE - SCRIPT',
                'color': 'COLOR',
                'view-more': 'Lihat lebih banyak',
                'booking': 'Pemesanan',
                'select-branch': 'Pilih Cabang',
                'select-artist': 'Pilih Artist',
                'select-date': 'Pilih Tanggal',
                'select-time': 'Pilih Waktu',
                'booking-summary': 'Ringkasan Pemesanan',
                'contact': 'Kontak',
                'testimonials': 'Apa Kata Pelanggan Kami',
                'available': 'Tersedia',
                'busy': 'Sibuk',
                'free': 'Bebas',
                'artists': 'Artis',
                'hours': 'Jam',
                'next': 'Selanjutnya',
                'previous': 'Sebelumnya',
                'confirm-booking': 'Konfirmasi Pemesanan',
                'home': 'Beranda',
                'studios': 'Studio',
                'reviews': 'Ulasan',
                'select-date-time': 'Pilih Tanggal & Waktu',
                'contact-information': 'Informasi Kontak',
                'full-name': 'Nama Lengkap',
                'email': 'Email',
                'whatsapp': 'WhatsApp',
                'tattoo-description': 'Deskripsi Tattoo (Opsional)',
                'summary': 'Ringkasan',
                'calendar': 'Kalender',
                'available-times': 'Waktu Tersedia',
                'studio': 'Studio',
                'uluwatu-studio': 'Studio Uluwatu',
                'canggu-studio': 'Studio Canggu',
                'denpasar-studio': 'Studio Denpasar',
                'your-session': 'Sesi Anda',
                'contact-us': 'Hubungi Kami',
                'phone': 'Telepon',
                'instagram': 'Instagram',
                'all-rights-reserved': 'Hak Cipta Dilindungi'
            },
            en: {
                'tattoo-studio': 'Tattoo Studio',
                'bali': 'Bali',
                'premium-locations': '3 Premium Locations: Uluwatu • Canggu • Denpasar',
                'book-now': 'Book Now',
                'view-portfolio': 'View Portfolio',
                'our-studios': 'Our Studios',
                'about-us': 'About Us',
                'our-story': 'Our Story',
                'our-story-text': 'INKBALI is a premier tattoo studio with three locations across Bali. We specialize in creating unique, high-quality tattoos that reflect your personal style and story. Our team of professional artists brings years of experience and artistic excellence to every piece.',
                'why-choose-us': 'Why Choose Us',
                'professional-artists': 'Professional artists with years of experience',
                'premium-quality': 'Premium quality inks and equipment',
                'sterile-safe': 'Sterile and safe environment',
                'convenient-locations': '3 convenient locations in Bali',
                'portfolio': 'Portfolio',
                'graywash-black-gray': 'GRAYWASH / BLACK AND GRAY',
                'small-fineline-script': 'SMALL - FINELINE - SCRIPT',
                'color': 'COLOR',
                'view-more': 'View more',
                'booking': 'Booking',
                'select-branch': 'Select Branch',
                'select-artist': 'Select Artist',
                'select-date': 'Select Date',
                'select-time': 'Select Time',
                'booking-summary': 'Booking Summary',
                'contact': 'Contact',
                'testimonials': 'What Our Customers Say',
                'available': 'Available',
                'busy': 'Busy',
                'free': 'Free',
                'artists': 'Artists',
                'hours': 'Hours',
                'next': 'Next',
                'previous': 'Previous',
                'confirm-booking': 'Confirm Booking',
                'home': 'Home',
                'studios': 'Studios',
                'reviews': 'Reviews',
                'select-date-time': 'Select Date & Time',
                'contact-information': 'Contact Information',
                'full-name': 'Full Name',
                'email': 'Email',
                'whatsapp': 'WhatsApp',
                'tattoo-description': 'Tattoo Description (Optional)',
                'summary': 'Summary',
                'calendar': 'Calendar',
                'available-times': 'Available Times',
                'studio': 'Studio',
                'uluwatu-studio': 'Uluwatu Studio',
                'canggu-studio': 'Canggu Studio',
                'denpasar-studio': 'Denpasar Studio',
                'your-session': 'Your Session',
                'contact-us': 'Contact Us',
                'phone': 'Phone',
                'instagram': 'Instagram',
                'all-rights-reserved': 'All Rights Reserved'
            }
        },
        
        // Template 7 (Dashboard)
        'dashboard': {
            id: {
                'dashboard': 'Dashboard',
                'overview': 'Ringkasan',
                'bookings': 'Pemesanan',
                'artists': 'Artis',
                'portfolio': 'Portfolio',
                'settings': 'Pengaturan',
                'total-bookings': 'Total Pemesanan',
                'pending': 'Menunggu',
                'confirmed': 'Dikonfirmasi',
                'completed': 'Selesai',
                'recent-bookings': 'Pemesanan Terbaru',
                'view-all': 'Lihat Semua'
            },
            en: {
                'dashboard': 'Dashboard',
                'overview': 'Overview',
                'bookings': 'Bookings',
                'artists': 'Artists',
                'portfolio': 'Portfolio',
                'settings': 'Settings',
                'total-bookings': 'Total Bookings',
                'pending': 'Pending',
                'confirmed': 'Confirmed',
                'completed': 'Completed',
                'recent-bookings': 'Recent Bookings',
                'view-all': 'View All'
            }
        }
    },
    
    getPageType() {
        const path = window.location.pathname;
        const href = window.location.href;
        
        // Check for template 8 or proposal
        if (path.includes('template-8') || path.includes('template%208') || href.includes('template-8') || href.includes('template%208')) {
            return 'proposal';
        }
        
        // Check for template 7 or dashboard
        if (path.includes('template-7') || path.includes('template%207') || href.includes('template-7') || href.includes('template%207')) {
            return 'dashboard';
        }
        
        // Check for template 4, 5 (frontend)
        if (path.includes('template-4') || path.includes('template%204') || path.includes('template-5') || path.includes('template%205') || 
            href.includes('template-4') || href.includes('template%204') || href.includes('template-5') || href.includes('template%205')) {
            return 'frontend';
        }
        
        // Check for bundle index
        if (path.includes('bundle') || path === '/' || path.endsWith('index.html') || path.endsWith('/') || href.includes('bundle/index')) {
            return 'bundle';
        }
        
        // Default to frontend for tattoo studio pages
        return 'frontend';
    },
    
    t(key, lang, pageType) {
        pageType = pageType || this.getPageType();
        lang = lang || 'id';
        return this.translations[pageType]?.[lang]?.[key] || key;
    }
};

